workflows:
  ios-build:
    name: iOS Build
    environment:
      node: 20
    scripts:
      - npm ci
      - chmod +x node_modules/.bin/expo
      - npx expo prebuild --platform ios
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.ipa
